title: DevOps Notes
description: A collection of DevOps projects and notes
author: Jatin Sharma
baseurl: "" # Empty for GitHub Pages
theme: minima # GitHub Pages default theme
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-toc
  - jekyll-sitemap
collections:
  devops:
    output: true
    permalink: /devops/:path/
