# title: Home
title: My Portfolio
logo: "./site-icon.webp"
# favicon_ico: "./favicon.ico"
description: 🌟 Welcome to My Portfolio - Showcasing expertise in Cloud, DevOps, Automation, and Cutting-Edge Technologies! 🚀
author: Jatin Sharma
github_username: kioskOG
theme: just-the-docs
color_scheme: dark
sass:
  quiet_deps: true

url: https://github.com/kioskOG/kioskOG.github.io

aux_links:
  Repository: https://github.com/kioskOG/kioskOG.github.io

aux_links_new_tab: true
search_enabled: true

search:
  focus_shortcut_key: 'k'

nav_enabled: true
heading_anchors: true

callouts_level: quiet # or loud # https://just-the-docs.com/docs/ui-components/callouts/
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
