apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  namespace: default
  annotations:
    cloudmap.controller/namespace: "test-namespace"
    cloudmap.controller/hostname: "nginx-test-service"
spec:
  clusterIP: None
  selector:
    app: nginx-test
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
