apiVersion: v1
kind: Service
metadata:
  name: nginx-3
  annotations:
    cloudmap.controller/namespace: "test-namespace"
    cloudmap.controller/hostname: "nginx-service-2"   # Cloud Map service name
    cloudmap.controller/ttl: "30"    # Optional: how it appears in Cloud Map
spec:
  clusterIP: None
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: nginx-3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-3
  template:
    metadata:
      labels:
        app: nginx-3
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http