apiVersion: v1
kind: Service
metadata:
  name: nginx-2
  namespace: default
  annotations:
    cloudmap.controller/namespace: "test-namespace"
    cloudmap.controller/hostname: "nginx-service-2"   # Cloud Map service name
    cloudmap.controller/ttl: "30"                     # DNS record TTL (seconds)
spec:
  clusterIP: None
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: nginx-2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-2
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http